---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  out.width = "100%"
)
```

The model can be used with the usual formula interface or using the `tidymodels` and `censored` structure.

Formula interface:

```{r example}
library(persistencia)

set.seed(1)
mod1 <- survival_ln_mixture(Surv(y, delta) ~ x, sim_data$data, intercept = TRUE)
mod1
```

Tidymodels approach:

```{r}
library(censored)
mod_spec <- survival_reg() |>
  set_engine("survival_ln_mixture", intercept = TRUE) |>
  set_mode("censored regression")
set.seed(1)
mod2 <- mod_spec |>
  fit(Surv(y, delta) ~ x, sim_data$data)
```

The estimates are easily obtained using tidy method. See `?tidy.survival_ln_mixture` for extra options.

```{r}
tidy(mod1)
tidy(mod2)
```


The predicitons are easy to obtain from a fit.

```{r prediction}
library(ggplot2)
library(purrr)
library(dplyr)
library(tidyr)

models <- list(formula = mod1, tidymodels = mod2)

new_data <- sim_data$data |> distinct(x)
pred_sob <- map(models, ~ predict(.x, new_data, type = "survival", eval_time = seq(120)))

bind_rows(pred_sob, .id = "modelo") %>%
  group_by(modelo) %>%
  dplyr::mutate(id = new_data$x) %>%
  ungroup() %>%
  tidyr::unnest(cols = .pred) %>%
  ggplot(aes(x = .eval_time, y = .pred_survival, col = id)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~modelo)
```
