---
title: "Posterior analysis with bayesplot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Posterior analysis with bayesplot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

A `survival_ln_mixture` object holds the posterior chain as a `?posterior::draws_matrix` object, and
can be analysed using the Stan ecosystem tools, like `bayesplot`.

```{r setup}
library(lnmixsurv)
library(bayesplot)
mod1 <- survival_ln_mixture(Surv(y, delta) ~ x, data = sim_data$data,
                            starting_seed = 1)

color_scheme_set('viridis')

mcmc_trace(mod1$posterior[, 'eta_1'])
```

Since the seed is fixed, we expect to obtain the same chain if e run the model again, with the same seed. We can make sure this is happening by look at a small portion of the chains.
```{r}
mod2 <- survival_ln_mixture(Surv(y, delta) ~ x, data = sim_data$data, 
                            starting_seed = 1)

mcmc_trace(posterior::subset_draws(mod1$posterior, iteration = 1:50,
                                   variable = 'eta_1'))

mcmc_trace(posterior::subset_draws(mod2$posterior, iteration = 1:50, 
                                   variable = 'eta_1'))
```
