# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom RcppParallel RcppParallelLibs
NULL

lognormal_mixture_gibbs <- function(Niter, em_iter, G, t, delta, X, a, starting_seed, show_output, n_chains, use_W, better_initial_values, N_em, Niter_em, fast_groups) {
    .Call(`_lnmixsurv_lognormal_mixture_gibbs`, Niter, em_iter, G, t, delta, X, a, starting_seed, show_output, n_chains, use_W, better_initial_values, N_em, Niter_em, fast_groups)
}

lognormal_mixture_em_implementation <- function(Niter, G, t, delta, X, starting_seed, better_initial_values, N_em, Niter_em) {
    .Call(`_lnmixsurv_lognormal_mixture_em_implementation`, Niter, G, t, delta, X, starting_seed, better_initial_values, N_em, Niter_em)
}

