# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sequential_lognormal_mixture_gibbs <- function(Niter, em_iter, G, chains, y, delta, X, a, show_output = FALSE) {
    .Call(`_lnmixsurv_sequential_lognormal_mixture_gibbs`, Niter, em_iter, G, chains, y, delta, X, a, show_output)
}

