# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs sampling for a two componentes mixture model
#'
#' @param y [nx1]
#' @param x [nxp]
#' @param delta [nx1]
#'
lognormal_mixture_gibbs_cpp <- function(y, x, delta, numero_iteracoes, valor_inicial_beta = 0) {
    .Call(`_persistencia_lognormal_mixture_gibbs_cpp`, y, x, delta, numero_iteracoes, valor_inicial_beta)
}

